/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fabrica.abtracta;

import objetos.arma;
import objetos.escudo;
import objetos.aspecto;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Kevin Garcia
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form vhg
     */
    public View() {
        initComponents();
    }

    fabricaAbstracta fab;
    arma arma1;
    escudo escudo1;
    aspecto aspecto1;
    ImageIcon imagenArma;
    ImageIcon imagenAspecto;
    ImageIcon imagenEscudo;
    ImageIcon icono1;
    ImageIcon icono2;
    ImageIcon icono3;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public class Dibuja {

        ImageIcon imagen;

        public void crearImagen(String ruta) {
            imagen = new ImageIcon(new ImageIcon(getClass().getResource(ruta)).getImage());
        }

        public void cargarImagen(Graphics g) {
            g.drawImage(imagen.getImage(), 0, 0, 100, 100, null);
        }

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        descripcionAspecto = new javax.swing.JLabel();
        descripcionArma = new javax.swing.JLabel();
        descripcionEscudo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        tanques = new javax.swing.JButton();
        Daños = new javax.swing.JButton();
        Flanco = new javax.swing.JButton();
        Soporte = new javax.swing.JButton();
        panelArma = new javax.swing.JPanel();
        panelAspecto = new javax.swing.JPanel();
        panelEscudo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Label1.setText("Catalogo de Personajes");

        descripcionAspecto.setText("Descripcion");

        descripcionArma.setText("Descripcion");

        descripcionEscudo.setText("Descripcion");

        tanques.setText("Tanques");
        tanques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanquesActionPerformed(evt);
            }
        });

        Daños.setText("Daño");
        Daños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DañosActionPerformed(evt);
            }
        });

        Flanco.setText("Flanco");
        Flanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlancoActionPerformed(evt);
            }
        });

        Soporte.setText("Soporte");
        Soporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelArmaLayout = new javax.swing.GroupLayout(panelArma);
        panelArma.setLayout(panelArmaLayout);
        panelArmaLayout.setHorizontalGroup(
            panelArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelArmaLayout.setVerticalGroup(
            panelArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelAspectoLayout = new javax.swing.GroupLayout(panelAspecto);
        panelAspecto.setLayout(panelAspectoLayout);
        panelAspectoLayout.setHorizontalGroup(
            panelAspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelAspectoLayout.setVerticalGroup(
            panelAspectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelEscudoLayout = new javax.swing.GroupLayout(panelEscudo);
        panelEscudo.setLayout(panelEscudoLayout);
        panelEscudoLayout.setHorizontalGroup(
            panelEscudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelEscudoLayout.setVerticalGroup(
            panelEscudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(descripcionAspecto, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(panelAspecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelArma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descripcionArma, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelEscudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descripcionEscudo, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addGap(56, 56, 56))
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(Label1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(tanques, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(Daños, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(Flanco, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(Soporte, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(Label1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descripcionAspecto, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(descripcionArma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descripcionEscudo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panelAspecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelEscudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanques, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Daños, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Soporte, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Flanco, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tanquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanquesActionPerformed
        fab = new fabricaTanques();       
        crearObjetos();
        ponerImagenes();       
        
             
        
    }//GEN-LAST:event_tanquesActionPerformed

    private void DañosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DañosActionPerformed
        fab = new fabricaDaños();
        crearObjetos();
        ponerImagenes(); 
    }//GEN-LAST:event_DañosActionPerformed

    private void FlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlancoActionPerformed
        fab = new fabricaFlancos();

        crearObjetos();
        ponerImagenes(); 
    }//GEN-LAST:event_FlancoActionPerformed

    private void SoporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoporteActionPerformed
        fab = new fabricaSoportes();
        crearObjetos();
        ponerImagenes(); 
    }//GEN-LAST:event_SoporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    public void crearObjetos() {
        arma1 = fab.crearArma();
        escudo1 = fab.crearEscudo();
        aspecto1 = fab.crearAspecto();
    }
    
    public void ponerImagenes(){
        
        Dibuja metodo = new Dibuja();
        
        descripcionArma.setText(arma1.descripcion);
        metodo.crearImagen(arma1.ubicacion);
        metodo.cargarImagen(panelArma.getGraphics());
        
        descripcionAspecto.setText(aspecto1.descripcion);
        metodo.crearImagen(aspecto1.ubicacion);
        metodo.cargarImagen(panelAspecto.getGraphics());
        
        descripcionEscudo.setText(escudo1.descripcion);
        metodo.crearImagen(escudo1.ubicacion);
        metodo.cargarImagen(panelEscudo.getGraphics());
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Daños;
    private javax.swing.JButton Flanco;
    private javax.swing.JLabel Label1;
    private javax.swing.JButton Soporte;
    private javax.swing.JLabel descripcionArma;
    private javax.swing.JLabel descripcionAspecto;
    private javax.swing.JLabel descripcionEscudo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelArma;
    private javax.swing.JPanel panelAspecto;
    private javax.swing.JPanel panelEscudo;
    private javax.swing.JButton tanques;
    // End of variables declaration//GEN-END:variables
}
